name: Updated CI

on: [push]

jobs:
  analysis:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:types
      - run: npm run test:unit
      - run: npm run deps:graph
      - uses: actions/upload-artifact@v1
        with:
          name: dependency-graph
          path: ./dependency-graph.svg
      - run: npm run deps:report
      - uses: actions/upload-artifact@v1
        with:
          name: dependency-report
          path: ./dependency-report.html

  unit:
    name: Unit
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run test:unit

  acceptance:
    name: End-to-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          start: npm start
